# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import array_pb2 as array__pb2


class ArrayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendArray = channel.unary_unary(
                '/array.ArrayService/SendArray',
                request_serializer=array__pb2.Array.SerializeToString,
                response_deserializer=array__pb2.Response.FromString,
                )


class ArrayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArrayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendArray': grpc.unary_unary_rpc_method_handler(
                    servicer.SendArray,
                    request_deserializer=array__pb2.Array.FromString,
                    response_serializer=array__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'array.ArrayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArrayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/array.ArrayService/SendArray',
            array__pb2.Array.SerializeToString,
            array__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
