# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rray.proto\x12\x05\x61rray\"\x17\n\x05\x41rray\x12\x0e\n\x06values\x18\x01 \x03(\x05\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\x05\x32<\n\x0c\x41rrayService\x12,\n\tSendArray\x12\x0c.array.Array\x1a\x0f.array.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'array_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARRAY']._serialized_start=22
  _globals['_ARRAY']._serialized_end=45
  _globals['_RESPONSE']._serialized_start=47
  _globals['_RESPONSE']._serialized_end=74
  _globals['_ARRAYSERVICE']._serialized_start=76
  _globals['_ARRAYSERVICE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
